server:
  port: 13000

zuul:
  routes:
    user-mgmt:
      path: /zhzg/user-mgmt/**
      serviceId: user-mgmt
#      sensitiveHeaders: "*"
    flow:
      path: /zhzg/flow/**
      serviceId: flow
    personnel:
      path: /zhzg/personnel/**
      serviceId: personnel
    multi:
      path: /zhzg/multi/**
      serviceId: multi
    statistics:
      path: /zhzg/statistics/**
      serviceId: statistics
    statistics2:
      path: /zhzg/statistics2/**
      serviceId: statistics2
    message:
      path: /zhzg/message/**
      serviceId: message
    personnel2:
      path: /zhzg/personnel2/**
      serviceId: personnel2
  #设置传递 content-leng  th header
  set-content-length: true
  sensitive-headers:
  max:
    host:
      connections: 2000
  host:
    #60000
    socket-timeout-millis: 100000
    #60000
    connect-timeout-millis: 100000
    maxTotalConnections: 100000
    maxPerRouteConnections: 10000
  semaphore:
    maxSemaphores: 1000
  ignored-services: '*'

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 160000
          semaphore.maxConcurrentRequests: 1000
eureka:
  client:
    healthcheck:
      enabled: false
  instance:
    leaseRenewalIntervalInSeconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb