spring:
  redis:
    host: 10.33.66.86
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@10.33.1.137:1521:qbgf1
    username: zhzg
    password: zhzg_2019
    driverClassName: oracle.jdbc.driver.OracleDriver
  data:
    mongodb:
      uri: mongodb://10.33.66.86:27017/zhzg

#eureka集群高可用，填写2个eureka的地址
cluster:
  eureka:
    ip: 10.33.66.86