spring:
  datasource:
    url: jdbc:mysql://10.10.10.212:3309/humanface_opencv?serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      properties:
        hibernate:
          show_sql: true
      hibernate:
        ddl-auto: none