spring:
  datasource:
    url: jdbc:mysql://10.10.10.23:3309/face?autoReconnect=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      properties:
        hibernate:
          show_sql: true
      hibernate:
        ddl-auto: none
origin:
  mysql:
    url: jdbc:mysql://10.10.10.23:3309/face?autoReconnect=true
    username: root
    password: root123
    driver: com.mysql.cj.jdbc.Driver